/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * BookData
 */
export interface BookData { 
    /**
     * Book format
     */
    format: BookData.FormatEnum;
    id?: number;
    /**
     * File name without extension
     */
    name: string;
    /**
     * Uncompressed size in bytes
     */
    uncompressedSize: number;
}
export namespace BookData {
    export const FormatEnum = {
        Epub: 'EPUB',
        Pdf: 'PDF',
        Mobi: 'MOBI',
        Azw3: 'AZW3',
        Fb2: 'FB2',
        Txt: 'TXT',
        Html: 'HTML',
        Rtf: 'RTF',
        Djvu: 'DJVU',
        Cbr: 'CBR',
        Cbz: 'CBZ'
    } as const;
    export type FormatEnum = typeof FormatEnum[keyof typeof FormatEnum];
}


