/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Constraint error
 */
export interface ConstraintError { 
    constraintsNotRespected?: Array<any>;
    /**
     * Field name
     */
    fieldName?: string;
}

