/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContentDisposition { 
    attachment?: boolean;
    charset?: string;
    /** @deprecated */
    creationDate?: string;
    filename?: string;
    formData?: boolean;
    inline?: boolean;
    /** @deprecated */
    modificationDate?: string;
    name?: string;
    /** @deprecated */
    readDate?: string;
    /** @deprecated */
    size?: number;
    type?: string;
}

