/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DefaultHttpStatusCode { 
    error?: boolean;
    is1xxInformational?: boolean;
    is2xxSuccessful?: boolean;
    is3xxRedirection?: boolean;
    is4xxClientError?: boolean;
    is5xxServerError?: boolean;
}

