/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorResponseHeadersHostAddress { 
    address?: string;
    anyLocalAddress?: boolean;
    canonicalHostName?: string;
    hostAddress?: string;
    hostName?: string;
    linkLocalAddress?: boolean;
    loopbackAddress?: boolean;
    mcglobal?: boolean;
    mclinkLocal?: boolean;
    mcnodeLocal?: boolean;
    mcorgLocal?: boolean;
    mcsiteLocal?: boolean;
    multicastAddress?: boolean;
    siteLocalAddress?: boolean;
}

