/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProblemDetail } from './problem-detail';
import { ErrorResponseStatusCode } from './error-response-status-code';
import { ErrorResponseHeaders } from './error-response-headers';


export interface ErrorResponse { 
    body?: ProblemDetail;
    detailMessageArguments?: Array<any>;
    detailMessageCode?: string;
    headers?: ErrorResponseHeaders;
    statusCode?: ErrorResponseStatusCode;
    titleMessageCode?: string;
    typeMessageCode?: string;
}

