/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseHeadersHostAddress } from './error-response-headers-host-address';


export interface ErrorResponseHeadersHost { 
    address?: ErrorResponseHeadersHostAddress;
    hostName?: string;
    hostString?: string;
    port?: number;
    unresolved?: boolean;
}

