/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefaultHttpStatusCode } from './default-http-status-code';
import { HttpStatus } from './http-status';


/**
 * @type ErrorResponseStatusCode
 * @export
 */
export type ErrorResponseStatusCode = DefaultHttpStatusCode | HttpStatus;

