/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentDisposition } from './content-disposition';
import { ErrorResponseHeadersAcceptLanguageInner } from './error-response-headers-accept-language-inner';
import { MediaType } from './media-type';
import { ErrorResponseHeadersHost } from './error-response-headers-host';


export interface ErrorResponseHeaders { 
  [key: string]: Array<string> | any;


    accept?: Array<MediaType>;
    acceptCharset?: Array<string>;
    acceptLanguage?: Array<ErrorResponseHeadersAcceptLanguageInner>;
    acceptLanguageAsLocales?: Array<string>;
    acceptPatch?: Array<MediaType>;
    accessControlAllowCredentials?: boolean;
    accessControlAllowHeaders?: Array<string>;
    accessControlAllowMethods?: Array<any>;
    accessControlAllowOrigin?: string;
    accessControlExposeHeaders?: Array<string>;
    accessControlMaxAge?: number;
    accessControlRequestHeaders?: Array<string>;
    accessControlRequestMethod?: any | null;
    all?: { [key: string]: string; };
    allow?: Set<any>;
    basicAuth?: string;
    bearerAuth?: string;
    cacheControl?: string;
    connection?: Array<string>;
    contentDisposition?: ContentDisposition;
    contentLanguage?: string;
    contentLength?: number;
    contentType?: MediaType;
    date?: number;
    empty?: boolean;
    etag?: string;
    expires?: number;
    host?: ErrorResponseHeadersHost;
    ifMatch?: Array<string>;
    ifModifiedSince?: number;
    ifNoneMatch?: Array<string>;
    ifUnmodifiedSince?: number;
    lastModified?: number;
    location?: string;
    origin?: string;
    pragma?: string;
    range?: Array<any>;
    upgrade?: string;
    vary?: Array<string>;
}

