/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConstraintError } from './constraint-error';
import { ErrorInternal } from './error-internal';


/**
 * Error data
 */
export interface ErrorData { 
    constraintErrors?: Array<ConstraintError>;
    internal?: ErrorInternal;
    /**
     * Description of error 
     */
    userMessage: string;
    /**
     * Title of error
     */
    userTitle: string;
}

