/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Library } from './library';


/**
 * LibraryInfo
 */
export interface LibraryInfo { 
    /**
     * Number of books in the library
     */
    booksCount: number;
    /**
     * Number of languages in the library
     */
    languagesCount: number;
    /**
     * Timestamp of the last book added to the library
     */
    lastBookAddedAt?: string;
    library?: Library;
    /**
     * Number of series in the library
     */
    seriesCount: number;
}

