/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * LibrariesInfo
 */
export interface LibrariesInfo { 
    /**
     * Number of authors
     */
    authors: number;
    /**
     * Number of books
     */
    books: number;
    /**
     * Number of languages
     */
    languages: number;
    /**
     * Number of publishers
     */
    publishers: number;
    /**
     * Number of series
     */
    series: number;
    /**
     * Number of tags
     */
    tags: number;
}

