/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaType { 
    charset?: string;
    concrete?: boolean;
    parameters?: { [key: string]: string; };
    qualityValue?: number;
    subtype?: string;
    subtypeSuffix?: string;
    type?: string;
    wildcardSubtype?: boolean;
    wildcardType?: boolean;
}

