/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProblemDetail { 
    detail?: string;
    instance?: string;
    properties?: { [key: string]: any; };
    status?: number;
    title?: string;
    type?: string;
}

