/**
 * LIBER-API
 *
 * Contact: gianluca.fattarsi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User information
 */
export interface UserInfo { 
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    userName: string;
}

